version: '3'

services:
  kong-db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kong_db
    ports:
      - 5432:5432
    networks:
      - kong
  kong-srv:
    image: kong:1.3.0-alpine
    environment:
      KONG_LOG_LEVEL: debug
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: kong_db
      KONG_CASSANDRA_CONTACT_POINTS: kong-db
      KONG_PG_USER: user
      KONG_PG_PASSWORD: 123456
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
    depends_on:
      - kong-db
      - kong-migration
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    networks:
      - kong
  kong-migration:
    image: kong:1.3.0-alpine
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: kong_db
      KONG_PG_USER: user
      KONG_PG_PASSWORD: 123456
      KONG_CASSANDRA_CONTACT_POINTS: kong-db
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    networks:
      - kong
  kong-admin-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://user:123456@kong-db:5432/konga_db"
    depends_on:
      - kong-db
    networks:
      - kong
  kong-admin:
    image: pantsel/konga:next
#    restart: always
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-db
      DB_USER: user
      DB_PASSWORD: 123456
      DB_DATABASE: konga_db
      TOKEN_SECRET: g4r4md1l4uTl3b1h45indAr1p4d4g4r4mRum4h
      KONGA_HOOK_TIMEOUT: 120000
      NODE_ENV: production
    depends_on:
      - kong-db
    ports:
      - 1337:1337
    networks:
      - kong
networks:
  kong:
    driver: bridge